default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: angi_pl_2020_development

test:
  <<: *default
  database: angi_pl_2020_test

production:
  <<: *default
  database: angi_pl_2020_production
  username:
  password:
